image: node:latest

variables:
  ANDROID_SDK_ROOT: "/usr/local/android-sdk"
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

before_script:
  - apt-get update && apt-get install -y openjdk-11-jdk
  - npm install -g @ionic/cli @capacitor/cli
  - npm install
  - ionic capacitor add android
  - ionic capacitor sync android

build_android:
  stage: build
  script:
    - ionic capacitor build android --no-open
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk 