image: node:latest

variables:
  ANDROID_SDK_ROOT: "/usr/local/android-sdk"
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

before_script:
  # Instalar dependências do sistema
  - apt-get update && apt-get install -y openjdk-11-jdk wget unzip
  
  # Instalar Android SDK
  - mkdir -p $ANDROID_SDK_ROOT
  - wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
  - unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_SDK_ROOT
  - yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.0"
  
  # Limpar e instalar dependências
  - npm cache clean --force
  - npm install -g @ionic/cli @capacitor/cli rimraf
  - npm install
  
  # Build do projeto
  - npm run build
  
  # Configurar Android
  - ionic capacitor add android
  - ionic capacitor sync android
  
  # Garantir que o gradlew seja executável
  - chmod +x android/gradlew

build_android:
  stage: build
  script:
    - cd android
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk

cache:
  paths:
    - node_modules/
    - .gradle/
    - android/.gradle/ 